# Site settings
title: Workshop on Data Science in Africa, 2015
email: 
description: > # this means to ignore newlines until "baseurl:"
  Data Science in Africa Workshop at DeKUT in Nyeri, Kenya.
baseurl: "/dsa15" # the subpath of your site, e.g. /blog/
url: "https://gpss.cc" # the base hostname & protocol for your site
twitter_username: datascienceshef
github_username:  SheffieldML
facebook_page: gaussianprocesssummerschool
analytics:
  google:
    tracking_id: UA-62991754-1

plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: gpschool/jekyll-theme
style: gpss

youtube:
  height: 315
  width: 560

conference:
  hosts:
  - {name: Ciira wa Maina, url: "https://sites.google.com/site/cwamainadekut/"}
  organizers:
  - {name: Ciira wa Maina, url: "https://sites.google.com/site/cwamainadekut/"}
  - {name: Neil Lawrence, url: "http://inverseprobability.com"}
  - {name: Andreas Damianou, url: "http://staffwww.dcs.sheffield.ac.uk/people/A.Damianou/index.html"}
  - {name: John Quinn, url: "http://air.ug/~jquinn/"}
  name: Data Science in Africa Workshop
  hosturl: https://sites.google.com/site/dekutdatascienceworkshop2015/
  location: Dedan Kimathi University of Technlogy, Nyeri, Kenya
  year: 2015
  month: June
  dates:
  - {date: 18, day: Thursday, month: June, year: 2015}
  - {date: 19, day: Friday, month: June, year: 2015}
  draft: N # set to Y if the programme is draft only.

# Build settings
markdown: kramdown

